DROP TABLE IF EXISTS FREE_REGISTRATION_ACCOUNT;
CREATE TABLE FREE_REGISTRATION_ACCOUNT (

  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY (
  START WITH 0 ) PRIMARY KEY,

  created_date            TIMESTAMP NOT NULL,
  last_modified_date      TIMESTAMP NOT NULL,

  username                VARCHAR(255),
  password                VARCHAR(255),
  email                   VARCHAR(255),
  first_name              VARCHAR(255),
  last_name               VARCHAR(255),
  display_name            VARCHAR(255),

  external_account_vendor VARCHAR(255),
  external_account_id     VARCHAR(255)

);